from django.contrib import admin
from django.contrib import admin
from . import models
# Register your models here.

admin.site.register(models.Administratorzy)
admin.site.register(models.CzynnosciPrzetwarzania)
admin.site.register(models.CzynnoscPrzetwarzania)
admin.site.register(models.CzynnoscPrzetwarzaniaDODO)
admin.site.register(models.CzynnoscPrzetwarzaniaRODO)
admin.site.register(models.GrupaZabezpieczen)
admin.site.register(models.GrupaZagrozen)
admin.site.register(models.KategoriaCzynnosciPrzetwarzaniaDODO)
admin.site.register(models.KategoriaCzynnosciPrzetwarzaniaRODO)
admin.site.register(models.KategorieDanych)
admin.site.register(models.KategorieOdbiorcow)
admin.site.register(models.KategoriaOsob)
admin.site.register(models.KategorieOsob)
admin.site.register(models.Komorka)
admin.site.register(models.KomorkiProfilu)
admin.site.register(models.OkresRetencji)
admin.site.register(models.OperacjePrzetwarzania)
admin.site.register(models.Organizacja)
admin.site.register(models.Profile)
admin.site.register(models.Podatnosc)
admin.site.register(models.PodmiotPrzetwarzajacy)
admin.site.register(models.PodmiotyPrzetwarzajace)
admin.site.register(models.PodstawaPrawnaPrzetwarzania)
admin.site.register(models.PrzeslankaLegalnosci)
admin.site.register(models.PrzeslankiLegalnosci)
admin.site.register(models.Rejestr)
admin.site.register(models.Ryzyko)
admin.site.register(models.SposobPrzetwarzania)
admin.site.register(models.SposobyPrzetwarzania)
admin.site.register(models.Wspoladministratorzy)
admin.site.register(models.WysokieRyzyko)
admin.site.register(models.WysokieRyzyka)
admin.site.register(models.Zagrozenie)
admin.site.register(models.ZakresOddzialywania)
