# Generated by Django 4.2.4 on 2023-09-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CzynnoscPrzetwarzania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("czn_sposoby_przetw", models.IntegerField()),
                ("czn_administratorzy", models.IntegerField()),
                ("czn_nazwa", models.CharField(max_length=200)),
                ("czn_pozycja_rej", models.IntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("czn_status_zatw", models.CharField(max_length=20)),
                ("czn_komorki", models.IntegerField()),
                ("czn_przepis_wrazliwe", models.TextField(max_length=200)),
                ("czn_podstawa_prawna", models.TextField(max_length=300)),
                ("czn_przeslanki_legalnosci", models.IntegerField()),
                ("czn_kategorie_danych", models.IntegerField()),
                ("czn_wspoladm", models.IntegerField()),
                ("czn_active", models.BooleanField(default=True)),
                ("czn_okres_retencji", models.TextField(max_length=100)),
                ("czn_podmioty_przetw", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("czn_zrodlo_danych", models.CharField(max_length=100)),
                ("czn_rej_id", models.IntegerField()),
                ("czn_opis_celu", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="KategoriaDanych",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kd_opis_danych", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("kd_dane_szczegolne", models.BooleanField()),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="KategoriaOsob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ko_nazwa_kat", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("ko_opis_kategorii", models.TextField(max_length=100)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="KategorieOdbiorcow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kat_opis_kategorii", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="OkresRetencji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("okr_nazwa", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("okr_opis_okresu", models.TextField(max_length=100)),
                ("okr_lat_max", models.DurationField()),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Organizacja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_iod_name", models.TextField(max_length=100)),
                ("org_nazwa", models.CharField(max_length=255)),
                ("org_adres", models.TextField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("org_www", models.URLField()),
                ("org_tel", models.TextField(max_length=100)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("org_iod_email", models.EmailField(max_length=254)),
                ("org_email", models.EmailField(max_length=254)),
                ("org_active", models.BooleanField(default=True)),
                ("org_skrot", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SposobPrzetwarzania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sp_opis", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="StatusZatwierdzenia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_opis", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="WysokieRyzyka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wr_nazwa", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("wr_opis_wys_ryzyka", models.TextField(max_length=100)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Zabezpieczenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZrodloDanych",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zd_opis_zrodla", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Rejestr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rej_opis", models.TextField(max_length=200)),
                ("rej_active", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("rej_zakres", models.CharField(max_length=30)),
                ("rej_nazwa", models.CharField(max_length=200)),
                ("rej_wlasciciel", models.IntegerField()),
                (
                    "Organizacja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rejestr.organizacja",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Komorka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("kom_adres", models.CharField(max_length=255)),
                ("kom_active", models.BooleanField(default=True)),
                ("kom_symbol", models.CharField(max_length=10)),
                ("kom_parent_org_id", models.IntegerField()),
                ("kom_tel", models.TextField(max_length=100)),
                ("kom_nazwa", models.CharField(max_length=255)),
                ("kom_email", models.EmailField(max_length=254)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "CzynnoscPrzetwarzania",
                    models.ManyToManyField(to="rejestr.czynnoscprzetwarzania"),
                ),
                (
                    "Organizacja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rejestr.organizacja",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="czynnoscprzetwarzania",
            name="Komorka",
            field=models.ManyToManyField(to="rejestr.komorka"),
        ),
        migrations.AddField(
            model_name="czynnoscprzetwarzania",
            name="czn_przeslanki_wys_ryz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rejestr.wysokieryzyka"
            ),
        ),
        migrations.AddField(
            model_name="czynnoscprzetwarzania",
            name="czn_zabezp_admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rejestr.organizacja"
            ),
        ),
        migrations.AddField(
            model_name="czynnoscprzetwarzania",
            name="czn_zabezp_transf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rejestr.zabezpieczenie"
            ),
        ),
    ]
