# Generated by Django 4.2.4 on 2023-09-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizacja",
            name="org_adres",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="organizacja",
            name="org_email",
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name="organizacja",
            name="org_iod_email",
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name="organizacja",
            name="org_www",
            field=models.URLField(max_length=100),
        ),
    ]
