# Generated by Django 4.2.4 on 2023-09-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0002_alter_organizacja_org_adres_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizacja",
            name="org_nazwa",
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name="organizacja",
            name="org_skrot",
            field=models.TextField(max_length=30),
        ),
    ]
