# Generated by Django 4.2.4 on 2023-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0003_alter_organizacja_org_nazwa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rejestr",
            name="rej_wlasciciel",
        ),
        migrations.AlterField(
            model_name="organizacja",
            name="org_adres",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="organizacja",
            name="org_iod_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="organizacja",
            name="org_skrot",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="organizacja",
            name="org_tel",
            field=models.CharField(max_length=100),
        ),
    ]
