# Generated by Django 4.2.4 on 2023-09-26 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0004_remove_rejestr_rej_wlasciciel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="komorka",
            name="kom_parent_org_id",
        ),
    ]
