# Generated by Django 4.2.4 on 2023-09-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0005_remove_komorka_kom_parent_org_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="komorka",
            name="CzynnoscPrzetwarzania",
        ),
        migrations.AlterField(
            model_name="komorka",
            name="kom_tel",
            field=models.CharField(max_length=100),
        ),
    ]
