# Generated by Django 4.2.4 on 2023-09-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0006_remove_komorka_czynnoscprzetwarzania_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kategoriadanych",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="kategoriaosob",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="kategorieodbiorcow",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="okresretencji",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="sposobprzetwarzania",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="statuszatwierdzenia",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="wysokieryzyka",
            name="slug",
        ),
        migrations.AlterField(
            model_name="kategoriaosob",
            name="ko_nazwa_kat",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="kategoriaosob",
            name="ko_opis_kategorii",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="wysokieryzyka",
            name="wr_nazwa",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="wysokieryzyka",
            name="wr_opis_wys_ryzyka",
            field=models.TextField(max_length=255),
        ),
    ]
