# Generated by Django 4.2.4 on 2023-09-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0008_remove_czynnoscprzetwarzania_czn_administratorzy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="czynnoscprzetwarzania",
            name="czn_status_zatw",
            field=models.CharField(
                choices=[
                    ("ZATWIERDZONA", "ZATWIERDZONA"),
                    ("ANULOWANA", "ANULOWANA"),
                    ("ODRZUCONA", "ODRZUCONA"),
                    ("OCZEKUJACA", "OCZEKUJACA"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
