# Generated by Django 4.2.4 on 2023-09-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0012_czynnoscprzetwarzania_rejestr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="okresretencji",
            name="okr_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="okresretencji",
            name="okr_opis_okresu",
            field=models.CharField(max_length=200),
        ),
    ]
