# Generated by Django 4.2.4 on 2023-09-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0013_okresretencji_okr_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="czynnoscprzetwarzania",
            name="Organizacja",
        ),
        migrations.AddField(
            model_name="sposobprzetwarzania",
            name="sp_active",
            field=models.BooleanField(default=True),
        ),
    ]
