# Generated by Django 4.2.4 on 2023-09-28 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0015_alter_okresretencji_okr_lat_max"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="okresretencji",
            options={},
        ),
    ]
