# Generated by Django 4.2.4 on 2023-09-28 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0016_alter_okresretencji_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ZrodloDanych",
        ),
    ]
