# Generated by Django 4.2.4 on 2023-09-28 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0017_delete_zrodlodanych"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StatusZatwierdzenia",
        ),
    ]
