# Generated by Django 4.2.4 on 2023-09-28 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0018_delete_statuszatwierdzenia"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Zabezpieczenie",
        ),
    ]
