# Generated by Django 4.2.4 on 2023-09-29 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0020_alter_czynnoscprzetwarzania_komorka_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rejestr",
            name="Organizacja",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rejestr.organizacja",
            ),
        ),
    ]
