# Generated by Django 4.2.4 on 2023-09-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0021_alter_rejestr_organizacja"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrzeslankaLegalnosci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prl_active", models.BooleanField(default=True, null=True)),
                ("prl_skrot", models.CharField(max_length=100)),
                ("prl_art_rodo", models.CharField(max_length=100)),
                ("prl_przepis_rodo", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
