# Generated by Django 4.2.4 on 2023-09-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0029_podmiotyprzetwarzajace"),
    ]

    operations = [
        migrations.AddField(
            model_name="czynnoscprzetwarzania",
            name="Administratorzy",
            field=models.ManyToManyField(
                through="rejestr.Administratorzy", to="rejestr.organizacja"
            ),
        ),
    ]
