# Generated by Django 4.2.4 on 2023-09-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0030_czynnoscprzetwarzania_administratorzy"),
    ]

    operations = [
        migrations.AddField(
            model_name="czynnoscprzetwarzania",
            name="Wspoladministratorzy",
            field=models.ManyToManyField(
                through="rejestr.Wspoladministratorzy", to="rejestr.organizacja"
            ),
        ),
        migrations.AlterField(
            model_name="administratorzy",
            name="adm_czynnoscp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adm_czynnosc_p",
                to="rejestr.czynnoscprzetwarzania",
            ),
        ),
        migrations.AlterField(
            model_name="administratorzy",
            name="adm_organizacja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adm_organizacja_f",
                to="rejestr.organizacja",
            ),
        ),
        migrations.AlterField(
            model_name="czynnoscprzetwarzania",
            name="Administratorzy",
            field=models.ManyToManyField(
                related_name="Organizacja_Administratorzy",
                through="rejestr.Administratorzy",
                to="rejestr.organizacja",
            ),
        ),
        migrations.AlterField(
            model_name="podmiotyprzetwarzajace",
            name="pod_czynnoscp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pod_czynnosc_p",
                to="rejestr.czynnoscprzetwarzania",
            ),
        ),
        migrations.AlterField(
            model_name="podmiotyprzetwarzajace",
            name="pod_organizacja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pod_organizacja_p",
                to="rejestr.organizacja",
            ),
        ),
        migrations.AlterField(
            model_name="wspoladministratorzy",
            name="wad_czynnoscp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wad_czynnosc_p",
                to="rejestr.czynnoscprzetwarzania",
            ),
        ),
        migrations.AlterField(
            model_name="wspoladministratorzy",
            name="wad_organizacja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wad_organizacja_f",
                to="rejestr.organizacja",
            ),
        ),
    ]
