# Generated by Django 4.2.4 on 2023-09-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0031_czynnoscprzetwarzania_wspoladministratorzy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="czynnoscprzetwarzania",
            name="PodmiotyPrzetwarzajace",
            field=models.ManyToManyField(
                related_name="Organizacja_PodmiotyPrzetwarzajace",
                through="rejestr.PodmiotyPrzetwarzajace",
                to="rejestr.organizacja",
            ),
        ),
        migrations.AlterField(
            model_name="czynnoscprzetwarzania",
            name="Wspoladministratorzy",
            field=models.ManyToManyField(
                related_name="Organizacja_Wspoladministratorzy",
                through="rejestr.Wspoladministratorzy",
                to="rejestr.organizacja",
            ),
        ),
    ]
