# Generated by Django 4.2.4 on 2023-09-30 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0033_sposobprzetwarzania_sp_skrot_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sposobprzetwarzania",
            options={},
        ),
        migrations.CreateModel(
            name="SposobyPrzetwarzania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spp_czynnoscp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spp_czynnosc_p",
                        to="rejestr.czynnoscprzetwarzania",
                    ),
                ),
                (
                    "spp_sposobp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spp_sposob_p",
                        to="rejestr.sposobprzetwarzania",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="czynnoscprzetwarzania",
            name="SposobPrzetwarzania",
            field=models.ManyToManyField(
                related_name="CzynnoscPrzetwarzania_SposobyPrzetwarzania",
                through="rejestr.SposobyPrzetwarzania",
                to="rejestr.sposobprzetwarzania",
            ),
        ),
    ]
