# Generated by Django 4.2.4 on 2023-09-30 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "rejestr",
            "0035_rename_sposobprzetwarzania_czynnoscprzetwarzania_sposobyprzetwarzania",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kategoriaosob",
            options={},
        ),
        migrations.RenameField(
            model_name="kategoriaosob",
            old_name="ko_opis_kategorii",
            new_name="ko_opis",
        ),
        migrations.RenameField(
            model_name="kategoriaosob",
            old_name="ko_nazwa_kat",
            new_name="ko_skrot",
        ),
    ]
