# Generated by Django 4.2.4 on 2023-09-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0036_alter_kategoriaosob_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kategoriadanych",
            options={},
        ),
        migrations.AlterModelOptions(
            name="kategorieodbiorcow",
            options={},
        ),
        migrations.RemoveField(
            model_name="kategoriadanych",
            name="kd_opis_danych",
        ),
        migrations.RemoveField(
            model_name="kategorieodbiorcow",
            name="kat_opis_kategorii",
        ),
        migrations.AddField(
            model_name="kategoriadanych",
            name="kd_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kategoriadanych",
            name="kd_opis",
            field=models.TextField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kategoriadanych",
            name="kd_skrot",
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kategoriaosob",
            name="ko_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kategorieodbiorcow",
            name="kto_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kategorieodbiorcow",
            name="kto_opis",
            field=models.TextField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kategorieodbiorcow",
            name="kto_skrot",
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
