# Generated by Django 4.2.4 on 2023-09-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0037_alter_kategoriadanych_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wysokieryzyka",
            options={},
        ),
        migrations.RenameField(
            model_name="wysokieryzyka",
            old_name="wr_opis_wys_ryzyka",
            new_name="wr_opis",
        ),
        migrations.RenameField(
            model_name="wysokieryzyka",
            old_name="wr_nazwa",
            new_name="wr_skrot",
        ),
        migrations.AddField(
            model_name="wysokieryzyka",
            name="wr_active",
            field=models.BooleanField(default=True),
        ),
    ]
