# Generated by Django 4.2.4 on 2023-09-30 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0038_alter_wysokieryzyka_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="KategorieOdbiorcow",
            new_name="KategoriaOdbiorcow",
        ),
    ]
