# Generated by Django 4.2.4 on 2023-10-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0039_rename_kategorieodbiorcow_kategoriaodbiorcow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kategoriadanych",
            name="kd_opis",
            field=models.TextField(max_length=300),
        ),
    ]
