# Generated by Django 4.2.4 on 2023-10-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0041_alter_wysokieryzyka_wr_opis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wysokieryzyka",
            name="wr_opis",
            field=models.TextField(max_length=400),
        ),
    ]
