# Generated by Django 4.2.4 on 2023-10-01 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0042_alter_wysokieryzyka_wr_opis"),
    ]

    operations = [
        migrations.CreateModel(
            name="WysokieRyzyko",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wr_active", models.BooleanField(default=True)),
                ("wr_skrot", models.CharField(max_length=100)),
                ("wr_opis", models.TextField(max_length=400)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        
        migrations.CreateModel(
            name="KategorieOsob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kos_czynnoscp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kos_czynnosc_p",
                        to="rejestr.czynnoscprzetwarzania",
                    ),
                ),
                (
                    "kos_kosoby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kos_kosoby_p",
                        to="rejestr.kategoriaosob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KategorieOdbiorcow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kob_czynnoscp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kob_czynnosc_p",
                        to="rejestr.czynnoscprzetwarzania",
                    ),
                ),
                (
                    "kob_odbiorcy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kob_odbiorcy_p",
                        to="rejestr.kategoriaodbiorcow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KategorieDanych",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ktd_czynnoscp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ktd_czynnosc_p",
                        to="rejestr.czynnoscprzetwarzania",
                    ),
                ),
                (
                    "ktd_dane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ktd_dane_p",
                        to="rejestr.kategoriadanych",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="czynnoscprzetwarzania",
            name="KategorieDanych",
            field=models.ManyToManyField(
                related_name="CzynnoscPrzetwarzania_KategoriaDanych",
                through="rejestr.KategorieDanych",
                to="rejestr.kategoriadanych",
            ),
        ),
        migrations.AddField(
            model_name="czynnoscprzetwarzania",
            name="KategorieOdbiorcow",
            field=models.ManyToManyField(
                related_name="CzynnoscPrzetwarzania_KategoriaOdbiorcow",
                through="rejestr.KategorieOdbiorcow",
                to="rejestr.kategoriaodbiorcow",
            ),
        ),
        migrations.AddField(
            model_name="czynnoscprzetwarzania",
            name="KategorieOsob",
            field=models.ManyToManyField(
                related_name="CzynnoscPrzetwarzania_KategoriaOsob",
                through="rejestr.KategorieOsob",
                to="rejestr.kategoriaosob",
            ),
        ),
        
    ]
