# Generated by Django 4.2.4 on 2023-10-01 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0043_wysokieryzyko_remove_wysokieryzyka_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wysokieryzyka",
            name="created",
        ),
        migrations.RemoveField(
            model_name="wysokieryzyka",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="wysokieryzyka",
            name="wr_active",
        ),
        migrations.RemoveField(
            model_name="wysokieryzyka",
            name="wr_opis",
        ),
        migrations.RemoveField(
            model_name="wysokieryzyka",
            name="wr_skrot",
        ),
        migrations.AddField(
            model_name="wysokieryzyka",
            name="wrr_czynnoscp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wrr_czynnosc_p",
                to="rejestr.czynnoscprzetwarzania",
            ),
        ),
        migrations.AddField(
            model_name="wysokieryzyka",
            name="wrr_wryzyka",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wrr_wryzyka_p",
                to="rejestr.wysokieryzyko",
            ),
        ),
    ]
