# Generated by Django 4.2.4 on 2023-10-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0046_remove_czynnoscprzetwarzania_przeslankalegalnosci_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="iod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
