# Generated by Django 4.2.4 on 2023-10-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0047_iod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="czynnoscprzetwarzania",
            name="Administratorzy",
            field=models.ManyToManyField(
                null=True,
                related_name="Organizacja_Administratorzy",
                through="rejestr.Administratorzy",
                to="rejestr.organizacja",
            ),
        ),
        migrations.AlterField(
            model_name="podmiotyprzetwarzajace",
            name="pod_czynnoscp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pod_czynnosc_p",
                to="rejestr.czynnoscprzetwarzania",
            ),
        ),
        migrations.AlterField(
            model_name="podmiotyprzetwarzajace",
            name="pod_organizacja",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pod_organizacja_p",
                to="rejestr.organizacja",
            ),
        ),
        migrations.AlterField(
            model_name="sposobyprzetwarzania",
            name="spp_czynnoscp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spp_czynnosc_p",
                to="rejestr.czynnoscprzetwarzania",
            ),
        ),
        migrations.AlterField(
            model_name="sposobyprzetwarzania",
            name="spp_sposobp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spp_sposob_p",
                to="rejestr.sposobprzetwarzania",
            ),
        ),
    ]
