# Generated by Django 4.2.4 on 2023-10-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0049_alter_kategoriedanych_ktd_czynnoscp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CzynnosciPrzetwarzania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "czp_czynnoscp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="czp_czynnosc_p",
                        to="rejestr.czynnoscprzetwarzania",
                    ),
                ),
                (
                    "czp_komorka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="czp_komorka_p",
                        to="rejestr.komorka",
                    ),
                ),
            ],
        ),
    ]
