# Generated by Django 4.2.4 on 2023-10-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0050_czynnosciprzetwarzania"),
    ]

    operations = [
        migrations.AlterField(
            model_name="czynnosciprzetwarzania",
            name="czp_czynnoscp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="czp_czynnosc_p",
                to="rejestr.czynnoscprzetwarzania",
            ),
        ),
        migrations.AlterField(
            model_name="czynnosciprzetwarzania",
            name="czp_komorka",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="czp_komorka_p",
                to="rejestr.komorka",
            ),
        ),
        migrations.AlterField(
            model_name="czynnoscprzetwarzania",
            name="Administratorzy",
            field=models.ManyToManyField(
                related_name="Organizacja_Administratorzy",
                through="rejestr.Administratorzy",
                to="rejestr.organizacja",
            ),
        ),
    ]
