# Generated by Django 4.2.4 on 2023-10-08 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0051_alter_czynnosciprzetwarzania_czp_czynnoscp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="czynnoscprzetwarzania",
            name="Komorka",
        ),
    ]
