# Generated by Django 4.2.4 on 2023-10-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rejestr", "0052_remove_czynnoscprzetwarzania_komorka"),
    ]

    operations = [
        migrations.AddField(
            model_name="czynnoscprzetwarzania",
            name="KomorkiRealizujace",
            field=models.ManyToManyField(
                related_name="CzynnoscPrzetwarzania_Komorki",
                through="rejestr.CzynnosciPrzetwarzania",
                to="rejestr.komorka",
            ),
        ),
        migrations.AddField(
            model_name="komorka",
            name="CzynnosciRealizowane",
            field=models.ManyToManyField(
                related_name="Komorki_CzynnosciPrzetwarzania",
                through="rejestr.CzynnosciPrzetwarzania",
                to="rejestr.czynnoscprzetwarzania",
            ),
        ),
    ]
