# Generated by Django 4.2.4 on 2023-10-20 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0054_alter_czynnoscprzetwarzania_komorkirealizujace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratorzy',
            name='adm_czynnoscp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adm_czynnosc_p', to='rejestr.czynnoscprzetwarzania'),
        ),
        migrations.AlterField(
            model_name='administratorzy',
            name='adm_organizacja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adm_organizacja_f', to='rejestr.organizacja'),
        ),
        migrations.AlterField(
            model_name='wspoladministratorzy',
            name='wad_czynnoscp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wad_czynnosc_p', to='rejestr.czynnoscprzetwarzania'),
        ),
        migrations.AlterField(
            model_name='wspoladministratorzy',
            name='wad_organizacja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wad_organizacja_f', to='rejestr.organizacja'),
        ),
    ]
