# Generated by Django 4.2.4 on 2023-10-20 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0055_alter_administratorzy_adm_czynnoscp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przeslankilegalnosci',
            name='ppl_czynnoscp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppl_czynnosc_p', to='rejestr.czynnoscprzetwarzania'),
        ),
        migrations.AlterField(
            model_name='przeslankilegalnosci',
            name='ppl_przeslankap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppl_przeslanka_p', to='rejestr.przeslankalegalnosci'),
        ),
    ]
