# Generated by Django 4.2.4 on 2023-10-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0056_alter_przeslankilegalnosci_ppl_czynnoscp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czynnoscprzetwarzania',
            name='KomorkiRealizujace',
            field=models.ManyToManyField(related_name='CzynnoscPrzetwarzania_Komorki', through='rejestr.CzynnosciPrzetwarzania', to='rejestr.komorka'),
        ),
    ]
