# Generated by Django 4.2.4 on 2023-10-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0057_alter_czynnoscprzetwarzania_komorkirealizujace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zabezpieczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zab_active', models.BooleanField(default=True)),
                ('zab_skrot', models.CharField(max_length=30)),
                ('zab_opis', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zagrozenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zag_active', models.BooleanField(default=True)),
                ('zag_skrot', models.CharField(max_length=30)),
                ('zag_opis', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
