# Generated by Django 4.2.4 on 2023-10-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0059_grupazabezpieczen_grupazagrozen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabezpieczenie',
            name='Odpowiedzialny',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rejestr.organizacja'),
        ),
        migrations.AddField(
            model_name='zabezpieczenie',
            name='Zagrozenie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rejestr.zagrozenie'),
        ),
    ]
