# Generated by Django 4.2.4 on 2023-10-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0060_zabezpieczenie_odpowiedzialny_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zabezpieczenie',
            name='GrupaZabezpieczen',
        ),
        migrations.AddField(
            model_name='zabezpieczenie',
            name='GrupyZabezpieczen',
            field=models.ManyToManyField(to='rejestr.grupazabezpieczen'),
        ),
    ]
