# Generated by Django 4.2.4 on 2023-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0062_remove_zabezpieczenie_zagrozenie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zabezpieczenie',
            name='Odpowiedzialny',
        ),
        migrations.AddField(
            model_name='zabezpieczenie',
            name='Odpowiedzialni',
            field=models.ManyToManyField(to='rejestr.organizacja'),
        ),
    ]
