# Generated by Django 4.2.4 on 2023-10-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0063_remove_zabezpieczenie_odpowiedzialny_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podatnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_skrot', models.CharField(max_length=30)),
                ('pdt_opis', models.CharField(max_length=300)),
                ('pdt_waga', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ryzyko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prawdopodobienstwo_bp', models.IntegerField(null=True)),
                ('Prawdopodobienstwo', models.IntegerField(null=True)),
                ('Oddzialywanie', models.IntegerField(null=True)),
                ('Ryzyko', models.IntegerField(null=True)),
                ('Redukcja', models.IntegerField(null=True)),
                ('Szczatkowe', models.IntegerField(null=True)),
                ('Postepowanie', models.CharField(max_length=30)),
                ('UzasadnieniePrawdopodobienstwa', models.CharField(max_length=500)),
                ('UzasadnienieOddzialywania', models.CharField(max_length=500)),
                ('UzasadnienieOddzialywania_atr', models.CharField(max_length=500)),
                ('UzasadnieniePostepowania', models.CharField(max_length=500)),
                ('AnalizaRyzyka', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ZakresOddzialywania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zao_Poufnosc', models.BooleanField(default=True)),
                ('zao_Integralnosc', models.BooleanField(default=True)),
                ('zao_Dostepnosc', models.BooleanField(default=True)),
                ('zao_Rozliczalnosc', models.BooleanField(default=True)),
                ('zao_CiagloscDzialania', models.BooleanField(default=True)),
                ('zao_StratyWizerunkowe', models.BooleanField(default=True)),
                ('zao_NaruszeniePrIW', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='zabezpieczenie',
            name='zab_waga',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zabezpieczenie',
            name='zab_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
