# Generated by Django 4.2.4 on 2023-10-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0065_ryzyko_zabezpieczenie_ryzyko_zagrozenie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podatnosc',
            name='Zagrozenie',
            field=models.ManyToManyField(to='rejestr.zagrozenie'),
        ),
    ]
