# Generated by Django 4.2.4 on 2023-10-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0066_podatnosc_zagrozenie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podatnosc',
            old_name='Zagrozenie',
            new_name='Zagrozenia',
        ),
        migrations.AddField(
            model_name='podatnosc',
            name='pdt_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='podatnosc',
            name='pdt_waga',
            field=models.IntegerField(default=0),
        ),
    ]
