# Generated by Django 4.2.4 on 2023-10-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0067_rename_zagrozenie_podatnosc_zagrozenia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ryzyko',
        ),
    ]
