# Generated by Django 4.2.4 on 2023-10-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0068_delete_ryzyko'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ryzyko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rr_SkalaPodatnosci', models.IntegerField(default=0)),
                ('rr_prawdopodobienstwo_bp', models.IntegerField(default=0)),
                ('rr_prawdopodobienstwo', models.IntegerField(default=0)),
                ('rr_odzialywanie', models.IntegerField(default=0)),
                ('rr_ryzyko', models.IntegerField(default=0)),
                ('rr_redukcja', models.IntegerField(default=0)),
                ('rr_szczatkowe', models.IntegerField(default=0)),
                ('rr_postepowanie', models.CharField(default='M', max_length=30)),
                ('rr_uzasadnieniePrawdopodobienstwa', models.CharField(max_length=500)),
                ('rr_uzasadnienieOddzialywania', models.CharField(max_length=500)),
                ('rr_uzasadnienieOddzialywania_atr', models.CharField(max_length=500)),
                ('rr_uzasadnieniePostepowania', models.CharField(max_length=500)),
                ('rr_analizaRyzyka', models.CharField(max_length=500)),
                ('Zabezpieczenia', models.ManyToManyField(to='rejestr.zabezpieczenie')),
                ('Zagrozenie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rejestr.zagrozenie')),
                ('ZakresOddzialywania', models.ManyToManyField(to='rejestr.zakresoddzialywania')),
            ],
        ),
    ]
