# Generated by Django 4.2.4 on 2023-11-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0069_ryzyko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zabezpieczenie',
            name='Zagrozenia',
        ),
    ]
