# Generated by Django 4.2.4 on 2024-01-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0070_remove_zabezpieczenie_zagrozenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacjePrzetwarzania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opp_czynnoscp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opp_czynnosc_p', to='rejestr.czynnoscprzetwarzania')),
                ('opp_operacjap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opp_operacjap_p', to='rejestr.przeslankalegalnosci')),
            ],
        ),
    ]
