# Generated by Django 4.2.4 on 2024-05-26 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0072_operacjaprzetwarzania_and_more'),
    ]

    operations = [
		migrations.RunSQL("delete from rejestr_podmiotyprzetwarzajace;"),
        migrations.CreateModel(
            name='PodmiotPrzetwarzajacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prz_active', models.BooleanField(default=True)),
                ('prz_skrot', models.CharField(max_length=30)),
                ('prz_nazwa', models.CharField(max_length=155)),
                ('prz_adres', models.CharField(max_length=100)),
                ('prz_email', models.EmailField(max_length=50)),
                ('prz_www', models.URLField(max_length=100)),
                ('prz_tel', models.CharField(max_length=100)),
                ('prz_iod_name', models.CharField(max_length=100)),
                ('prz_iod_email', models.EmailField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='zabezpieczenie',
            name='komorka',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='czynnoscprzetwarzania',
            name='PodmiotyPrzetwarzajace',
            field=models.ManyToManyField(related_name='PodmiotPrzetw_PodmiotyPrzetwarzajace', through='rejestr.PodmiotyPrzetwarzajace', to='rejestr.podmiotprzetwarzajacy'),
        ),
        migrations.AlterField(
            model_name='podmiotyprzetwarzajace',
            name='pod_organizacja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pod_pprzetw_p', to='rejestr.podmiotprzetwarzajacy'),
        ),
    ]
