# Generated by Django 4.2.4 on 2024-05-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0073_podmiotprzetwarzajacy_zabezpieczenie_komorka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='czynnoscprzetwarzania',
            name='czn_data_obowazywania_do',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='czynnoscprzetwarzania',
            name='czn_data_obowazywania_od',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='czynnoscprzetwarzania',
            name='czn_data_wyrejestrowania',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='czynnoscprzetwarzania',
            name='czn_data_zgloszenia',
            field=models.DateField(null=True),
        ),
    ]
