# Generated by Django 5.1 on 2024-09-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0074_czynnoscprzetwarzania_czn_data_obowazywania_do_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czynnoscprzetwarzania',
            name='czn_data_obowazywania_do',
            field=models.DateField(null=True),
        ),
    ]
