# Generated by Django 5.1 on 2024-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0075_alter_czynnoscprzetwarzania_czn_data_obowazywania_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czynnoscprzetwarzania',
            name='czn_pozycja_rej',
            field=models.IntegerField(null=True),
        ),
    ]
