# Generated by Django 5.1.1 on 2024-09-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0076_alter_czynnoscprzetwarzania_czn_pozycja_rej'),
    ]

    operations = [
        migrations.CreateModel(
            name='CzynnoscPrzetwarzaniaDODO',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rejestr.czynnoscprzetwarzania',),
        ),
        migrations.CreateModel(
            name='CzynnoscPrzetwarzaniaRODO',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rejestr.czynnoscprzetwarzania',),
        ),
        migrations.CreateModel(
            name='KategoriaCzynnosciPrzetwarzaniaDODO',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rejestr.czynnoscprzetwarzania',),
        ),
        migrations.CreateModel(
            name='KategoriaCzynnosciPrzetwarzaniaRODO',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rejestr.czynnoscprzetwarzania',),
        ),
    ]
