# Generated by Django 5.1.1 on 2024-10-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czynnoscprzetwarzania',
            name='czn_status_zatw',
            field=models.CharField(choices=[(None, '-----------'), ('OCZEKUJĄCA', 'Oczekuje na zatwierdzenie'), ('ZATWIERDZONA', 'Zatwierdzona i obowiązująca'), ('ODRZUCONA', 'Odrzucona po rozpatrzeniu'), ('ANULOWANA', 'Anulowana i nieobowiązująca')], max_length=20, null=True),
        ),
    ]
