# Generated by Django 5.1.1 on 2024-10-26 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0003_alter_czynnoscprzetwarzania_czn_zrodlo_danych'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='komorka',
            name='kom_symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='KomorkiProfilu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpu_komorka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpu_komorka', to='rejestr.komorka')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUzytkownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_active', models.BooleanField(default=True, null=True)),
                ('pro_nazwa', models.CharField(max_length=225)),
                ('pro_opis', models.CharField(max_length=225)),
                ('pro_rodo', models.BooleanField(default=True, null=True)),
                ('pro_policyjna', models.BooleanField(default=True, null=True)),
                ('pro_avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('pro_rola', models.CharField(choices=[(None, '-----------'), ('KIERA', 'Kierujacy komórką'), ('NUS', 'Naczelnik Urzędu'), ('DIAS', 'Dyrektor IAS'), ('IOD IAS', 'IOD Izby'), ('IOD US', 'IOD Urzędu Skarbowego'), ('IOD UCS', 'IOD Urzędu Celno Skarbowego'), ('AUD IAS', 'Audytor IAS')], max_length=50, null=True)),
                ('pro_komorki', models.ManyToManyField(related_name='ProfilUzytkownika_Komorki', through='rejestr.KomorkiProfilu', to='rejestr.komorka')),
                ('pro_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='komorkiprofilu',
            name='kpu_profil_u',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpu_profil_u', to='rejestr.profiluzytkownika'),
        ),
    ]
