# Generated by Django 5.1.1 on 2024-10-26 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0004_alter_komorka_kom_symbol_komorkiprofilu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiluzytkownika',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiluzytkownika',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
