# Generated by Django 5.1.1 on 2024-10-30 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0005_profiluzytkownika_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administratorzy',
            options={'verbose_name': 'M2M Administratorzy', 'verbose_name_plural': 'M2M Administratorzy'},
        ),
        migrations.AlterModelOptions(
            name='czynnosciprzetwarzania',
            options={'verbose_name': 'M2M Czynności przetwarzania DODO', 'verbose_name_plural': 'M2M Czynności przetwarzania DODO'},
        ),
        migrations.AlterModelOptions(
            name='czynnoscprzetwarzania',
            options={'verbose_name': 'Czynność przetwarzania', 'verbose_name_plural': 'Czynności przetwarzania'},
        ),
        migrations.AlterModelOptions(
            name='czynnoscprzetwarzaniadodo',
            options={'verbose_name': 'Czynność przetwarzania DODO', 'verbose_name_plural': 'Czynności przetwarzania DODO'},
        ),
        migrations.AlterModelOptions(
            name='czynnoscprzetwarzaniarodo',
            options={'verbose_name': 'Czynność przetwarzania RODO', 'verbose_name_plural': 'Czynności przetwarzania RODO'},
        ),
        migrations.AlterModelOptions(
            name='grupazabezpieczen',
            options={'verbose_name': 'Grupa zabezpieczeń', 'verbose_name_plural': 'Grupy zabezpieczeń'},
        ),
        migrations.AlterModelOptions(
            name='grupazagrozen',
            options={'verbose_name': 'Grupa zagrożeń', 'verbose_name_plural': 'Grupy zagrożeń'},
        ),
        migrations.AlterModelOptions(
            name='kategoriaczynnosciprzetwarzaniadodo',
            options={'verbose_name': 'Kategorie czynności przetwarzania DODO', 'verbose_name_plural': 'Kategorie czynności przetwarzania DODO'},
        ),
        migrations.AlterModelOptions(
            name='kategoriaczynnosciprzetwarzaniarodo',
            options={'verbose_name': 'Kategorie Czynności przetwarzania RODO', 'verbose_name_plural': 'Czynności przetwarzania RODO'},
        ),
        migrations.AlterModelOptions(
            name='kategoriadanych',
            options={'verbose_name': 'Kategoria danych', 'verbose_name_plural': 'Kategorie danych'},
        ),
        migrations.AlterModelOptions(
            name='kategoriaodbiorcow',
            options={'verbose_name': 'Kategoria odbiorców', 'verbose_name_plural': 'Kategorie odbiorców'},
        ),
        migrations.AlterModelOptions(
            name='kategoriaosob',
            options={'verbose_name': 'Kategoria osób', 'verbose_name_plural': 'Kategorie osób'},
        ),
        migrations.AlterModelOptions(
            name='kategoriedanych',
            options={'verbose_name': 'M2M Kategorie Danych', 'verbose_name_plural': 'M2M Kategorie Danych'},
        ),
        migrations.AlterModelOptions(
            name='kategorieodbiorcow',
            options={'verbose_name': 'M2M Kategorie odbiorców', 'verbose_name_plural': 'M2M Kategorie odbiorców'},
        ),
        migrations.AlterModelOptions(
            name='kategorieosob',
            options={'verbose_name': 'M2M Kategorie osób', 'verbose_name_plural': 'M2M Kategorie osób'},
        ),
        migrations.AlterModelOptions(
            name='komorka',
            options={'verbose_name': 'Komórka', 'verbose_name_plural': 'Komórki'},
        ),
        migrations.AlterModelOptions(
            name='komorkiprofilu',
            options={'verbose_name': 'Komorka profilu', 'verbose_name_plural': 'Komorki profili'},
        ),
        migrations.AlterModelOptions(
            name='okresretencji',
            options={'verbose_name': 'Okres retencji', 'verbose_name_plural': 'Okresy retencji'},
        ),
        migrations.AlterModelOptions(
            name='operacjaprzetwarzania',
            options={'verbose_name': 'Operacja przetwarzania', 'verbose_name_plural': 'Operacje przetwarzania'},
        ),
        migrations.AlterModelOptions(
            name='organizacja',
            options={'verbose_name': 'Organizacja', 'verbose_name_plural': 'Organizacje'},
        ),
        migrations.AlterModelOptions(
            name='podatnosc',
            options={'verbose_name': 'Podatność', 'verbose_name_plural': 'Podatności'},
        ),
        migrations.AlterModelOptions(
            name='podmiotprzetwarzajacy',
            options={'verbose_name': 'Podmiot przetwarzający', 'verbose_name_plural': 'Podmioty przetwarzające'},
        ),
        migrations.AlterModelOptions(
            name='podmiotyprzetwarzajace',
            options={'verbose_name': 'M2M Podmioty Przetwarzające', 'verbose_name_plural': 'M2M Podmioty Przetwarzające'},
        ),
        migrations.AlterModelOptions(
            name='podstawaprawnaprzetwarzania',
            options={'verbose_name': 'Podstawa prawna przetwarzania', 'verbose_name_plural': 'Podstawy prawna przetwarzania'},
        ),
        migrations.AlterModelOptions(
            name='profiluzytkownika',
            options={'verbose_name': 'Profil użytkownika', 'verbose_name_plural': 'Profile uzytkowników'},
        ),
        migrations.AlterModelOptions(
            name='przeslankalegalnosci',
            options={'verbose_name': 'Przesłanka legalności', 'verbose_name_plural': 'Przesłanki legalności'},
        ),
        migrations.AlterModelOptions(
            name='przeslankilegalnosci',
            options={'verbose_name': 'Przesłanki legalności', 'verbose_name_plural': 'Przesłanki legalności'},
        ),
        migrations.AlterModelOptions(
            name='rejestr',
            options={'verbose_name': 'Rejestr', 'verbose_name_plural': 'Rejestry'},
        ),
        migrations.AlterModelOptions(
            name='ryzyko',
            options={'verbose_name': 'Ryzyko', 'verbose_name_plural': 'Ryzyka'},
        ),
        migrations.AlterModelOptions(
            name='sposobprzetwarzania',
            options={'verbose_name': 'Sposób przetwarzania', 'verbose_name_plural': 'Sposoby przetwarzania'},
        ),
        migrations.AlterModelOptions(
            name='sposobyprzetwarzania',
            options={'verbose_name': 'M2M Sposoby Przetwarzania', 'verbose_name_plural': 'M2M Sposoby Przetwarzania'},
        ),
        migrations.AlterModelOptions(
            name='wspoladministratorzy',
            options={'verbose_name': 'M2M Współadministratorzy', 'verbose_name_plural': 'M2M Współadministratorzy'},
        ),
        migrations.AlterModelOptions(
            name='wysokieryzyka',
            options={'verbose_name': 'M2M Wysokie ryzyka', 'verbose_name_plural': 'M2M Wysokie ryzyka'},
        ),
        migrations.AlterModelOptions(
            name='wysokieryzyko',
            options={'verbose_name': 'Wysokie ryzyko', 'verbose_name_plural': 'Wysokie ryzyka'},
        ),
        migrations.AlterModelOptions(
            name='zabezpieczenie',
            options={'verbose_name': 'Zabezpieczenie', 'verbose_name_plural': 'Zabezpieczenia'},
        ),
        migrations.AlterModelOptions(
            name='zagrozenie',
            options={'verbose_name': 'Zagrożenie', 'verbose_name_plural': 'Zagrożenia'},
        ),
        migrations.AlterModelOptions(
            name='zakresoddzialywania',
            options={'verbose_name': 'Zakres Oddziaływania', 'verbose_name_plural': 'Zakresy Oddziaływania'},
        ),
        migrations.AlterField(
            model_name='grupazabezpieczen',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 17, 27, 45, 217193)),
        ),
        migrations.AlterField(
            model_name='grupazabezpieczen',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 17, 27, 45, 217193)),
        ),
    ]
