# Generated by Django 5.1.1 on 2024-11-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0008_remove_komorkiprofilu_kpu_profil_u_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacja',
            name='org_kod',
            field=models.CharField(default='2001-IWD', max_length=30),
        ),
    ]
