# Generated by Django 5.1.1 on 2024-11-03 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0010_remove_komorka_czynnoscirealizowane_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiluzytkownika',
            name='pro_active',
        ),
        migrations.AddField(
            model_name='profiluzytkownika',
            name='pro_organizacja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rejestr.organizacja'),
        ),
    ]
