# Generated by Django 5.1.1 on 2024-11-03 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0011_remove_profiluzytkownika_pro_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiluzytkownika',
            name='pro_komorka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rejestr.komorka'),
        ),
    ]
