# Generated by Django 5.1.1 on 2024-11-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0013_rename_profiluzytkownika_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacja',
            name='org_kod',
            field=models.CharField(default='2001-', max_length=30),
        ),
    ]
