# Generated by Django 5.1.1 on 2024-12-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0014_alter_organizacja_org_kod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podstawaprawnaprzetwarzania',
            options={'verbose_name': 'Podstawa prawna przetwarzania', 'verbose_name_plural': 'Podstawy prawne przetwarzania'},
        ),
    ]
