# Generated by Django 5.1.1 on 2024-12-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0015_alter_podstawaprawnaprzetwarzania_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='czynnoscprzetwarzania',
            name='czn_status_zatw',
        ),
        migrations.CreateModel(
            name='PozycjaRejestru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_active', models.BooleanField(default=True, null=True)),
                ('pre_pozycja_rej', models.IntegerField(null=True)),
                ('pre_status_zatw', models.CharField(choices=[(None, '-----------'), ('OCZEKUJĄCA', 'Oczekuje na zatwierdzenie'), ('ZATWIERDZONA', 'Zatwierdzona i obowiązująca'), ('ODRZUCONA', 'Odrzucona po rozpatrzeniu'), ('ANULOWANA', 'Anulowana i nieobowiązująca')], max_length=20, null=True)),
                ('pre_data_zgloszenia', models.DateField(null=True)),
                ('pre_data_wyrejestrowania', models.DateField(null=True)),
                ('pre_czynnoscp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_czynnosc_p', to='rejestr.czynnoscprzetwarzania')),
            ],
        ),
    ]
