# Generated by Django 5.1.1 on 2024-12-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0017_remove_czynnoscprzetwarzania_czn_data_zgloszenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='czynnoscprzetwarzania',
            name='czn_data_obowazywania_do',
        ),
        migrations.RemoveField(
            model_name='czynnoscprzetwarzania',
            name='czn_data_obowazywania_od',
        ),
        migrations.RemoveField(
            model_name='czynnoscprzetwarzania',
            name='czn_data_wyrejestrowania',
        ),
    ]
