# Generated by Django 5.1.1 on 2024-12-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0019_remove_czynnoscprzetwarzania_czn_pozycja_rej'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='czynnoscprzetwarzania',
            name='Rejestr',
        ),
    ]
