# Generated by Django 5.1.1 on 2024-12-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0021_remove_czynnoscprzetwarzania_komorkirealizujace'),
    ]

    operations = [
        migrations.AddField(
            model_name='czynnoscprzetwarzania',
            name='czn_dane_wrazliwe',
            field=models.BooleanField(default=False),
        ),
    ]
