# Generated by Django 5.1.1 on 2024-12-07 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0022_czynnoscprzetwarzania_czn_dane_wrazliwe'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanaWrazliwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdw_opis', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dana wrażliwa',
                'verbose_name_plural': 'Dane wrażliwe',
            },
        ),
        migrations.CreateModel(
            name='DaneWrazliwe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdw_czynnoscp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdw_czynnosc_p', to='rejestr.czynnoscprzetwarzania')),
                ('rdw_dane_w', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdw_danew_p', to='rejestr.kategoriadanych')),
            ],
            options={
                'verbose_name': 'M2M Dane wrażliwe',
                'verbose_name_plural': 'M2M Dane wrażliwe',
            },
        ),
    ]
